DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS preferences;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    passw TEXT NOT NULL
);

CREATE TABLE tasks (
    TID INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER NOT NULL,
    task TEXT NOT NULL,
    dateOfTaskStart DATETIME NOT NULL,
    dateOfTaskEnd DATETIME NOT NULL,
    duration INTEGER NOT NULL
);

CREATE TABLE preferences(
    PID INTEGER PRIMARY KEY AUTOINCREMENT,
    dayOfTime TEXT NOT NULL
);